### ISSUE TITLE
case insensitive

### ISSUE THREAD

**Issue by sergiokessler** [hernad/atom-language-harbour#5]
hi, how I can change the plugin to be case insentitive with respect to harbour keywords ?

I like to write in lowercase...

**Comment by hernad** [comment]
Hi,
I have used lowercase syntax earlier also, but decided to accept code formating standards from harbour community.
Anyway, you can change the grammar  here https://github.com/hernad/atom-language-harbour/blob/master/grammars/harbour.cson
