### ISSUE TITLE
lost of syntax highlight after a strange line

### ISSUE THREAD

**Issue by APerricone** [hernad/atom-language-harbour#7]
Hello,
working on my code I found this line, after its the syntax highlight does not work:
`METHOD aBitmap( n )      INLINE ( If( n > 0 .and. n <= 10, 5 , nil ) )`
The strange thing is it returns after a `>`...

I tried to understand why, but I am not able to do this.

Antonino

**Comment by hernad** [comment]
there is type parameter in C, something like 
<var>, which doesn't exists in harbour as we know :)

It seems ok with last version 3.3.4
